#!/bin/sh

xset s noblank
xset s off
xset -dpms

# Default to the default page if not URL found
kiosk_url=$(cat ~/kiosk-url.txt)
kiosk_location=$(cat ~/kiosk-location.txt)

if [ -n "$kiosk_url" ]; then
	# Use the, possibly dynamic, URL from file
	# TODO Validate the URL aswell
	url="$kiosk_url"
else
	# Use the default page and fill out the makeshift jinja tags (hehe..)
	model="$(tr -d '\0' < /sys/firmware/devicetree/base/model)"
	serial="$(tr -d '\0' < /sys/firmware/devicetree/base/serial-number)"
	hostname="$(hostname)"
	# TODO Prevent hardcoding ethernet device name here..
	mac="$(tr -d '\0' < /sys/class/net/eth0/address)"
	ipaddrs="$(hostname --all-ip-addresses)"

	# Yes, this sed command hurts a bit to write, but KISS for now
	default_page="/home/rocky/default-page.html"
	cat "$default_page.template" | \
		sed -e "s/{{hostname}}/$hostname/g" \
			-e "s/{{model}}/$model/g" \
			-e "s/{{serial}}/$serial/g" \
			-e "s/{{mac}}/$mac/g" \
			-e "s/{{ipaddrs}}/$ipaddrs/g" \
			-e "s/{{location}}/$kiosk_location/g" \
		>$default_page

	[ -f "$default_page" ] || { \
		cp $default_page.template $default_page; \
		echo "Did not find filled in default page, using template.."; \
	}

	url="file://$(readlink -f $default_page)"
fi

x_offset=0
y_offset=0
x_padding=0
y_padding=0
x_scale=1
y_scale=1

dims="$(xdpyinfo | grep -oP 'dimensions:\s+\K\S+')"
[[ -z "$dims" ]] && { echo "Got no dimensions, defaulting HD"; dims="1080x1920"; }

raw_width="$(echo $dims | cut -d 'x' -f 1)"
raw_height="$(echo $dims | cut -d 'x' -f 2)"

x="$(($x_offset + $x_padding))"
y="$(($y_offset + $y_padding))"
width="$(($x_scale * $raw_width - 2 * $x_padding))"
height="$(($y_scale * $raw_height - 2 * $y_padding))"

echo "Using position ($x, $y) with size ($width, $height) for chromium"

exec chromium-browser \
	--window-position="$x,$y" \
	--window-size="$width,$height" \
	--start-fullscreen \
	--start-maximized \
	--fast \
	--incognito \
	--no-default-browser-check \
	--noerrdialogs \
	--ignore-certificate-errors \
	--disable-translate \
	--disable-infobars \
	--kiosk \
	$url
